from Bio import SeqIO
from Bio.SeqUtils import molecular_weight
from Bio.SeqUtils.ProtParam import ProteinAnalysis

record = SeqIO.read("sequence.fasta","fasta")
print(record.id)
print(record.description)
print(len(record.seq))
print(record.seq)

mw = molecular_weight(record, seq_type="protein")
print("molecular_weight:", mw)

analysis = ProteinAnalysis(str(record))
print("Isoelectric Point:", analysis.isoelectric_point)
print("Aromaticity:", analysis.aromaticity)
print("GRAVYt:", analysis.gravy)

Alanine_count_A = record.seq.count("A")
Cysteine_count_C = record.seq.count("C")
Aspartate_count_D = record.seq.count("D")
Glutamate_count_E = record.seq.count("E")
Phenylalanine_count_F = record.seq.count("F")
Glycine_count_G = record.seq.count("G")
Histidine_count_H = record.seq.count("H")
Isolecine_count_I = record.seq.count("I")
Lysine_count_K = record.seq.count("K")
Leucine_count_L = record.seq.count("L")
Methonine_count_M = record.seq.count("M")
Aspargine_count_N = record.seq.count("N")
Proline_count_P = record.seq.count("P")
Glutamine_count_Q = record.seq.count("Q")
Arginine_count_R = record.seq.count("R")
Serine_count_S = record.seq.count("S")
Thereonine_count_T = record.seq.count("T")
Valine_count_V = record.seq.count("V")
Tryptophan_count_W = record.seq.count("W")
Tyrosine_count_Y = record.seq.count("Y")
Stopcodon_count = record.seq.count("#")

print("Alanine count is:", Alanine_count_A)
print("Cysteine count is:", Cysteine_count_C)
print("Aspartate count is:", Aspartate_count_D)
print("Glutamate count is:", Glutamate_count_E)
print("Phenylalanine count is:", Phenylalanine_count_F)
print("Glycine count is:", Glycine_count_G)
print("Histidine count is:", Histidine_count_H)
print("Isolecine count is:", Isolecine_count_I)
print("Lysine count is:", Lysine_count_K)
print("Leucine count is:", Leucine_count_L)
print("Methonine count is:", Methonine_count_M)
print("Aspargine count is:", Aspargine_count_N)
print("Proline count is:", Proline_count_P)
print("Serine count is:", Serine_count_S)
print("Threonine count is:", Thereonine_count_T)
print("Valine count is:", Valine_count_V)
print("Tryptophan count is:", Tryptophan_count_W)
print("Tyrosine count is:", Tyrosine_count_Y)
print("The query protein is", len(record.seq), "amino acids long.")